[package]
name = "water"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.15.1", features = ["dynamic_linking", "trace_tracy"]}
bevy_flycam = "0.15.0"
parking_lot = "0.12.3"
rayon = "1.10.0"

[profile.release]
debug = true
